#define WIN32_LEAN_AND_MEAN
#undef _WIN32_WINNT
#define _WIN32_WINNT 0x0601
#include <winsock2.h>
#include <windows.h>
#include <mmsystem.h>
#include <GL/gl.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "legacy_runtime.h"
#include "core.h"
#define PORT 27016
#define MAGIC 0x44535431u
#define VERSION 3
static World world;
static Input inputs[16];
static HWND window;
static HDC dc;
static HGLRC glrc;
static int width=1024,height=768,running=1,mode=0,myId=0,joinEdit=0,skipJoinChar=0,focused=1,help=0,dedicated=0;
static int botDifficulty=1; /* 0 easy, 1 normal, 2 hard */
static int shopOpen=0,pendingBuy=0;
static int resolutionIndex=1,graphicsQuality=2,fullScreen=0,settingsOpen=0,rebindIndex=-1;
static RECT savedWindowRect;
static DWORD savedWindowStyle=WS_OVERLAPPEDWINDOW;
static const int resolutions[5][2]={{800,600},{1024,768},{1280,720},{1600,900},{1920,1080}};
static int keys[256];
static int moveKeys[4]={'W','S','A','D'};
static char address[80]="127.0.0.1",statusText[160]="Original desert arena / 16 players / no bombs";
static float aimYaw,aimPitch,shotFlash=0,damageFlash=0,bob=0;
static GLuint tex[4],font,arenaList;
static SOCKET sock=INVALID_SOCKET;
static struct sockaddr_in serverAddr,peers[16];
static uint32_t tokens[16],sequences[16],clientToken=0,clientSeq=0,lastSnapTick=0;
static double lastSeen[16],lastInput[16],lastServer=0,nextHello=0,netNext=0;
static uint32_t seenShots[16];
static LARGE_INTEGER frequency;
static unsigned char gunSound[4][44+1600];
static void rebuildArena(void);
static void ellipsoid(float,float,float,float,float,float,float,float,float);
static double now(void){LARGE_INTEGER x;QueryPerformanceCounter(&x);return (double)x.QuadPart/frequency.QuadPart;}
static uint32_t random32(void){static uint32_t x=0;if(!x)x=GetTickCount()^GetCurrentProcessId()^0x721ff113;x^=x<<13;x^=x>>17;x^=x<<5;return x?x:1;}
static int samePeer(struct sockaddr_in *a,struct sockaddr_in *b){return a->sin_addr.s_addr==b->sin_addr.s_addr&&a->sin_port==b->sin_port;}
#include "network.h"
static void releaseMouse(void){ClipCursor(NULL);while(ShowCursor(TRUE)<0){}}
static void captureMouse(void){if(!window||!focused)return;RECT r;GetClientRect(window,&r);POINT a={r.left,r.top},b={r.right,r.bottom};ClientToScreen(window,&a);ClientToScreen(window,&b);r.left=a.x;r.top=a.y;r.right=b.x;r.bottom=b.y;ClipCursor(&r);SetCursorPos((a.x+b.x)/2,(a.y+b.y)/2);while(ShowCursor(FALSE)>=0){}}
static void menu(const char *message){if(mode==3&&clientToken){Input empty={0};sendRequest(5,empty);}mode=0;stopNet();releaseMouse();if(message)snprintf(statusText,sizeof(statusText),"%s",message);}
static void startGame(int m){initWorld(&world);rebuildArena();shopOpen=pendingBuy=0;memset(inputs,0,sizeof(inputs));memset(seenShots,0,sizeof(seenShots));myId=0;aimYaw=aimPitch=0;clientSeq=lastSnapTick=0;netNext=0;joinEdit=0;if(m==3){if(!openNet(0)){menu("Could not open a network socket.");return;}memset(&serverAddr,0,sizeof(serverAddr));serverAddr.sin_family=AF_INET;serverAddr.sin_port=htons(PORT);serverAddr.sin_addr.s_addr=inet_addr(address);if(serverAddr.sin_addr.s_addr==INADDR_NONE){menu("Enter a valid IPv4 address.");return;}myId=-1;lastServer=now();nextHello=0;}else{if(m==2&&!openNet(1)){menu("Port 27016 is busy. Close the other host first.");return;}addPlayer(&world,0);aimYaw=world.p[0].yaw;if(m==1)for(int j=1;j<8;j++)addPlayer(&world,j);}mode=m;captureMouse();}
static void clientNetwork(double t){if(myId<0&&t>=nextHello){Input zero={0};sendRequest(1,zero);nextHello=t+.5;}for(int k=0;k<64;k++){Snapshot s;struct sockaddr_in from;int size=sizeof(from);int n=recvfrom(sock,(char*)&s,sizeof(s),0,(struct sockaddr*)&from,&size);if(n<0)break;if(n!=sizeof(s)||!samePeer(&from,&serverAddr)||s.magic!=MAGIC||s.version!=VERSION)continue;if(s.type==4){menu("Server is full (16 players).");return;}if(s.type!=2||s.id<0||s.id>=16)continue;if(clientToken&&s.token!=clientToken)continue;if(myId>=0&&(int32_t)(s.w.tick-lastSnapTick)<0)continue;int first=myId<0;myId=s.id;clientToken=s.token;lastServer=t;lastSnapTick=s.w.tick;int wasDead=world.p[myId].hp<=0;int changedMap=selectedMap!=(int)s.w.mapId;world=s.w;selectedMap=(int)world.mapId;if(changedMap)rebuildArena();if(first||(wasDead&&world.p[myId].hp>0)){aimYaw=world.p[myId].yaw;aimPitch=0;}}
if(t-lastServer>10)menu("Connection timed out. Check IP, UDP 27016 and firewall.");}
/* Grid BFS lets practice opponents navigate the complete arena. */
static Input botInput(int id){Input r={0};Player *p=&world.p[id];r.yaw=p->yaw;int target=-1;float best=1e9f;for(int i=0;i<16;i++){Player *q=&world.p[i];if(!q->active||q->hp<=0||p->team==q->team)continue;float dx=q->x-p->x,dz=q->z-p->z,d=dx*dx+dz*dz;if(d<best){best=d;target=i;}}if(target<0)return r;Player *q=&world.p[target];if(best<2500&&visible(p,q)){float error=botDifficulty==0?.30f:botDifficulty==1?.14f:.055f;uint32_t noise=(world.tick*1103515245u+(uint32_t)id*12345u)>>16;r.yaw=atan2f(q->x-p->x,q->z-p->z)+(((int)(noise%2001)-1000)/1000.0f)*error;r.pitch=-.035f;r.buttons=(world.tick%(botDifficulty==0?30:botDifficulty==1?18:11)==(uint32_t)id%11)?1:0;r.forward=best>100?1:0;}else{int start=(int)(p->z/CELL)*32+(int)(p->x/CELL),goal=(int)(q->z/CELL)*32+(int)(q->x/CELL);int prev[1024],queue[1024],head=0,tail=0;for(int i=0;i<1024;i++)prev[i]=-1;prev[start]=start;queue[tail++]=start;while(head<tail&&prev[goal]<0){int a=queue[head++],x=a%32,z=a/32;int ox[4]={1,-1,0,0},oz[4]={0,0,1,-1};for(int k=0;k<4;k++){int nx=x+ox[k],nz=z+oz[k],b=nz*32+nx;if(nx<0||nx>=32||nz<0||nz>=32||tile(nx,nz)!='.'||prev[b]>=0)continue;prev[b]=a;queue[tail++]=b;}}if(prev[goal]>=0&&goal!=start){int b=goal;while(prev[b]!=start&&prev[b]!=b)b=prev[b];float tx=(b%32+.5f)*CELL,tz=(b/32+.5f)*CELL;r.yaw=atan2f(tx-p->x,tz-p->z);r.forward=1;}}
if(!p->ammo)r.buttons|=2;return r;}
static void soundInit(void){static const float gain[4]={1.0f,.62f,.34f,.15f};unsigned char *b=gunSound[0];memcpy(b,"RIFF",4);uint32_t n=sizeof(gunSound[0])-8;memcpy(b+4,&n,4);memcpy(b+8,"WAVEfmt ",8);n=16;memcpy(b+16,&n,4);uint16_t v=1;memcpy(b+20,&v,2);memcpy(b+22,&v,2);n=16000;memcpy(b+24,&n,4);memcpy(b+28,&n,4);memcpy(b+32,&v,2);v=8;memcpy(b+34,&v,2);memcpy(b+36,"data",4);n=1600;memcpy(b+40,&n,4);for(int i=0;i<1600;i++){float decay=1-(float)i/1600;b[44+i]=(unsigned char)(128+((int)(random32()%200)-100)*decay*decay);}for(int k=1;k<4;k++){memcpy(gunSound[k],gunSound[0],sizeof(gunSound[0]));for(int i=0;i<1600;i++)gunSound[k][44+i]=(unsigned char)(128+((int)gunSound[0][44+i]-128)*gain[k]);}}
static void playGunSound(float distance){if(distance>72)return;int band=distance<14?0:distance<32?1:distance<52?2:3;PlaySoundA((LPCSTR)gunSound[band],NULL,SND_MEMORY|SND_ASYNC|SND_NODEFAULT);}
static float hashNoise(int x,int y){uint32_t n=(uint32_t)x*0x8da6b343u^(uint32_t)y*0xd8163841u;n^=n>>13;n*=0x85ebca6bu;n^=n>>16;return (float)(n&65535u)/65535.0f;}
static float smoothNoise(float x,float y,int scale){float fx=x*scale,fy=y*scale;int ix=(int)floorf(fx),iy=(int)floorf(fy);float u=fx-ix,v=fy-iy;u=u*u*(3-2*u);v=v*v*(3-2*v);float a=hashNoise(ix,iy),b=hashNoise(ix+1,iy),c=hashNoise(ix,iy+1),d=hashNoise(ix+1,iy+1);return (a+(b-a)*u)+((c+(d-c)*u)-(a+(b-a)*u))*v;}
static void createTextures(void){int size=graphicsQuality==0?64:graphicsQuality==1?128:256;glGenTextures(4,tex);for(int k=0;k<4;k++){unsigned char pixels[256*256*3];int base[4][3]={{181,151,119},{161,139,106},{122,83,53},{76,88,96}};int unit=size/4;for(int y=0;y<size;y++)for(int x=0;x<size;x++){float u=(float)x/size,v=(float)y/size;float broad=smoothNoise(u,v,4),mid=smoothNoise(u,v,13),fine=smoothNoise(u,v,37);float detail=(broad-.5f)*24+(mid-.5f)*18+(fine-.5f)*11+(hashNoise(x,y)-.5f)*9;float shade=1.0f;int seam=0;if(k==0){int row=y/unit,withinY=y%unit;int mortarThickness=1+(int)(hashNoise(row,71)*2);int shifted=x+(row&1)*(unit/2);int withinX=shifted%unit;seam=withinY<mortarThickness||withinX<1+(int)(hashNoise(row,shifted/unit)*2);if(seam)shade=.66f;detail+=(broad-.5f)*10;}else if(k==1){detail+=(broad-.5f)*28+(mid-.5f)*10;shade=1.0f;}else if(k==2){float grain=(smoothNoise(u,v,5)-.5f)*25+(smoothNoise(u,v,29)-.5f)*12;detail=grain+(hashNoise(x,y)-.5f)*8;shade=1.0f;}else{float brushed=smoothNoise(u,v,43);detail=(brushed-.5f)*19+(mid-.5f)*9;shade=1.0f;}if(seam)detail*=.30f;for(int c=0;c<3;c++){float tint=(c-1)*(broad-.5f)*7;pixels[(y*size+x)*3+c]=(unsigned char)clampf(base[k][c]*shade+detail+tint,0,255);}}glBindTexture(GL_TEXTURE_2D,tex[k]);glTexImage2D(GL_TEXTURE_2D,0,GL_RGB,size,size,0,GL_RGB,GL_UNSIGNED_BYTE,pixels);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,graphicsQuality==0?GL_NEAREST:GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,graphicsQuality==0?GL_NEAREST:GL_LINEAR);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_REPEAT);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_REPEAT);}}
static void face(float a,float b,float c,float d,float e,float f,float g,float h,float i,float j,float k,float l,float u,float v){float ux=d-a,uy=e-b,uz=f-c,vx=g-a,vy=h-b,vz=i-c,nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx,len=sqrtf(nx*nx+ny*ny+nz*nz);if(len>.0001f)glNormal3f(-nx/len,-ny/len,-nz/len);glTexCoord2f(0,0);glVertex3f(a,b,c);glTexCoord2f(u,0);glVertex3f(d,e,f);glTexCoord2f(u,v);glVertex3f(g,h,i);glTexCoord2f(0,v);glVertex3f(j,k,l);}
static void box(float x,float y,float z,float sx,float sy,float sz,int texture,float r,float g,float b){if(texture>=0){glEnable(GL_TEXTURE_2D);glBindTexture(GL_TEXTURE_2D,tex[texture]);}else glDisable(GL_TEXTURE_2D);float X=x+sx,Y=y+sy,Z=z+sz;glBegin(GL_QUADS);glColor3f(r*.78f,g*.78f,b*.78f);face(x,y,z,X,y,z,X,Y,z,x,Y,z,sx/3,sy/3);face(X,y,Z,x,y,Z,x,Y,Z,X,Y,Z,sx/3,sy/3);glColor3f(r*.9f,g*.9f,b*.9f);face(x,y,Z,x,y,z,x,Y,z,x,Y,Z,sz/3,sy/3);face(X,y,z,X,y,Z,X,Y,Z,X,Y,z,sz/3,sy/3);glColor3f(r,g,b);face(x,Y,z,X,Y,z,X,Y,Z,x,Y,Z,sx/3,sz/3);face(x,y,Z,X,y,Z,X,y,z,x,y,z,sx/3,sz/3);glEnd();}
static void textAt(float x,float y,float size,const char *s,float r,float g,float b){glDisable(GL_TEXTURE_2D);glColor3f(r,g,b);glPushMatrix();glTranslatef(x,y,0);glScalef(size,size,1);glRasterPos2f(0,0);glListBase(font);glCallLists((GLsizei)strlen(s),GL_UNSIGNED_BYTE,s);glPopMatrix();}
static void rect(float x,float y,float w,float h,float r,float g,float b,float a){glDisable(GL_TEXTURE_2D);glColor4f(r,g,b,a);glBegin(GL_QUADS);glVertex2f(x,y);glVertex2f(x+w,y);glVertex2f(x+w,y+h);glVertex2f(x,y+h);glEnd();}
static void ortho(void){glDisable(GL_DEPTH_TEST);glDisable(GL_FOG);glDisable(GL_LIGHTING);glMatrixMode(GL_PROJECTION);glLoadIdentity();glOrtho(0,width,height,0,-1,1);glMatrixMode(GL_MODELVIEW);glLoadIdentity();glEnable(GL_BLEND);glBlendFunc(GL_SRC_ALPHA,GL_ONE_MINUS_SRC_ALPHA);}
static void perspective(float fov){glMatrixMode(GL_PROJECTION);glLoadIdentity();double top=.08*tan(fov*PI/360);glFrustum(-top*width/height,top*width/height,-top,top,.08,180);glMatrixMode(GL_MODELVIEW);glLoadIdentity();}
/* Original masonry arches and domed roof silhouettes above walkable space. */
static void arch(float cx,float z,float radius){
 glEnable(GL_TEXTURE_2D);glBindTexture(GL_TEXTURE_2D,tex[0]);
 for(int i=0;i<18;i++){float a=PI*i/18,b=PI*(i+1)/18,inner=radius,outer=radius+.55f;
 float x0=cx+cosf(a)*inner,y0=2.8f+sinf(a)*inner,x1=cx+cosf(b)*inner,y1=2.8f+sinf(b)*inner;
 float X0=cx+cosf(a)*outer,Y0=2.8f+sinf(a)*outer,X1=cx+cosf(b)*outer,Y1=2.8f+sinf(b)*outer;
 glBegin(GL_QUADS);glColor3f(.90f,.86f,.76f);face(x0,y0,z,x1,y1,z,X1,Y1,z,X0,Y0,z,1,1);face(X0,Y0,z+.65f,X1,Y1,z+.65f,x1,y1,z+.65f,x0,y0,z+.65f,1,1);
 glColor3f(.58f,.53f,.43f);face(x0,y0,z+.65f,x1,y1,z+.65f,x1,y1,z,x0,y0,z,1,1);glEnd();}
}
static void dome(float cx,float y,float z,float radius){glDisable(GL_TEXTURE_2D);for(int ring=0;ring<7;ring++){float a=PI*.5f*ring/7,b=PI*.5f*(ring+1)/7;glColor3f(.40f+ring*.025f,.51f+ring*.02f,.49f+ring*.015f);glBegin(GL_QUAD_STRIP);for(int i=0;i<=24;i++){float p=2*PI*i/24;glNormal3f(cosf(p)*cosf(a),sinf(a),sinf(p)*cosf(a));glVertex3f(cx+cosf(p)*cosf(a)*radius,y+sinf(a)*radius,z+sinf(p)*cosf(a)*radius);glNormal3f(cosf(p)*cosf(b),sinf(b),sinf(p)*cosf(b));glVertex3f(cx+cosf(p)*cosf(b)*radius,y+sinf(b)*radius,z+sinf(p)*cosf(b)*radius);}glEnd();}}
static void buildArena(void){glEnable(GL_TEXTURE_2D);glBindTexture(GL_TEXTURE_2D,tex[1]);glColor3f(1,1,1);glBegin(GL_QUADS);face(0,0,0,96,0,0,96,0,96,0,0,96,8,8);glEnd();for(int z=0;z<32;z++)for(int x=0;x<32;x++){int c=tile(x,z);if(c=='#'){float h=5.5f;if(x==0||z==0||x==31||z==31)h=7.5f;if(graphicsQuality==0)box(x*CELL,0,z*CELL,CELL,h,CELL,0,1,1,1);else{box(x*CELL-.06f,0,z*CELL-.06f,CELL+.12f,.42f,CELL+.12f,0,.82f,.77f,.68f);box(x*CELL,.32f,z*CELL,CELL,h-.48f,CELL,0,1,1,1);box(x*CELL-.05f,h-.22f,z*CELL-.05f,CELL+.10f,.22f,CELL+.10f,0,.78f,.74f,.67f);}}else if(c=='c')box(x*CELL,0,z*CELL,CELL,2.6f,CELL,2,1,1,1);}
arch(13.5f,21.2f,4.5f);arch(37.5f,54.2f,4.5f);arch(70.5f,69.2f,4.5f);
box(45,5.5f,24,6,3,6,0,.86f,.86f,.83f);dome(48,8.5f,27,3.4f);
box(21,5.5f,60,3,5,3,0,.87f,.85f,.80f);box(20.7f,9.3f,59.7f,3.6f,.3f,3.6f,0,.66f,.63f,.56f);dome(22.5f,10.5f,61.5f,1.65f);
/* Wooden beams bridge passages; decoration never blocks walkable cells. */
for(int z=9;z<18;z+=3)box(22*CELL,4.5f,z*CELL,9,.28f,.3f,2,.8f,.8f,.8f);
for(int i=0;i<6;i++){float x=2.0f+i*15;box(x,7.5f,.4f,1,1.1f,1,0,.9f,.9f,.9f);}
/* Quality-dependent masonry edging replaces extra clutter props. */
}
static void rebuildArena(void){if(!glrc)return;if(arenaList)glDeleteLists(arenaList,1);arenaList=glGenLists(1);glNewList(arenaList,GL_COMPILE);buildArena();glEndList();}
static int applyResolution(void){int rw=resolutions[resolutionIndex][0],rh=resolutions[resolutionIndex][1];if(fullScreen){DEVMODEA dm;memset(&dm,0,sizeof(dm));dm.dmSize=sizeof(dm);dm.dmPelsWidth=(DWORD)rw;dm.dmPelsHeight=(DWORD)rh;dm.dmFields=DM_PELSWIDTH|DM_PELSHEIGHT;if(ChangeDisplaySettingsA(&dm,CDS_FULLSCREEN)!=DISP_CHANGE_SUCCESSFUL){snprintf(statusText,sizeof(statusText),"That fullscreen resolution is not supported.");return 0;}SetWindowPos(window,HWND_TOP,0,0,rw,rh,SWP_FRAMECHANGED|SWP_SHOWWINDOW);}else{RECT r={0,0,rw,rh};DWORD style=(DWORD)GetWindowLongA(window,GWL_STYLE);AdjustWindowRect(&r,style,FALSE);RECT old;GetWindowRect(window,&old);SetWindowPos(window,NULL,old.left,old.top,r.right-r.left,r.bottom-r.top,SWP_NOZORDER|SWP_NOACTIVATE|SWP_FRAMECHANGED);}return 1;}
static void toggleFullscreen(void){if(!fullScreen){GetWindowRect(window,&savedWindowRect);savedWindowStyle=(DWORD)GetWindowLongA(window,GWL_STYLE);fullScreen=1;if(!applyResolution()){fullScreen=0;return;}SetWindowLongA(window,GWL_STYLE,WS_POPUP|WS_VISIBLE);SetWindowPos(window,HWND_TOP,0,0,resolutions[resolutionIndex][0],resolutions[resolutionIndex][1],SWP_FRAMECHANGED|SWP_SHOWWINDOW);}else{ChangeDisplaySettingsA(NULL,0);fullScreen=0;SetWindowLongA(window,GWL_STYLE,(LONG)savedWindowStyle);RECT r={0,0,resolutions[resolutionIndex][0],resolutions[resolutionIndex][1]};AdjustWindowRect(&r,savedWindowStyle,FALSE);SetWindowPos(window,NULL,savedWindowRect.left,savedWindowRect.top,r.right-r.left,r.bottom-r.top,SWP_NOZORDER|SWP_FRAMECHANGED|SWP_SHOWWINDOW);}}
static void cycleGraphicsQuality(void){graphicsQuality=(graphicsQuality+1)%3;if(!glrc)return;glDeleteTextures(4,tex);createTextures();rebuildArena();}
static void drawShadow(float x,float z,float rx,float rz){if(graphicsQuality==0)return;glDisable(GL_LIGHTING);glDisable(GL_TEXTURE_2D);glEnable(GL_BLEND);glBlendFunc(GL_SRC_ALPHA,GL_ONE_MINUS_SRC_ALPHA);glBegin(GL_TRIANGLE_FAN);glColor4f(.02f,.015f,.01f,.28f);glVertex3f(x,.035f,z);for(int i=0;i<=24;i++){float a=2*PI*i/24;glColor4f(.02f,.015f,.01f,0);glVertex3f(x+cosf(a)*rx,.035f,z+sinf(a)*rz);}glEnd();glDisable(GL_BLEND);if(graphicsQuality>=2)glEnable(GL_LIGHTING);}
static void ellipsoid(float x,float y,float z,float rx,float ry,float rz,float r,float g,float b){glDisable(GL_TEXTURE_2D);glColor3f(r,g,b);int rings=graphicsQuality>=2?9:6,slices=graphicsQuality>=2?20:12;for(int i=0;i<rings;i++){float a=-PI*.5f+PI*i/rings,bb=-PI*.5f+PI*(i+1)/rings;glBegin(GL_QUAD_STRIP);for(int j=0;j<=slices;j++){float t=2*PI*j/slices,c=cosf(t),s=sinf(t);glNormal3f(c*cosf(a),sinf(a),s*cosf(a));glVertex3f(x+rx*c*cosf(a),y+ry*sinf(a),z+rz*s*cosf(a));glNormal3f(c*cosf(bb),sinf(bb),s*cosf(bb));glVertex3f(x+rx*c*cosf(bb),y+ry*sinf(bb),z+rz*s*cosf(bb));}glEnd();}}
static void drawPlayer(Player *p){static float lastX[MAX_PLAYERS],lastZ[MAX_PLAYERS],stride[MAX_PLAYERS];static int known[MAX_PLAYERS];int id=(int)(p-&world.p[0]);float dx=p->x-lastX[id],dz=p->z-lastZ[id];if(!known[id])known[id]=1;else if(dx*dx+dz*dz>.0004f)stride[id]=1.0f;else stride[id]=fmaxf(0,stride[id]-.06f);lastX[id]=p->x;lastZ[id]=p->z;float r=p->team?.75f:.28f,g=p->team?.53f:.48f,b=p->team?.28f:.64f;float phase=(float)world.tick*.11f+p->x*.7f+p->z*.3f,walk=sinf(phase)*.20f*stride[id],bounce=fabsf(sinf(phase))*.045f*stride[id];drawShadow(p->x,p->z,.52f,.38f);glPushMatrix();glTranslatef(p->x,bounce,p->z);glRotatef(p->yaw*180/PI,0,1,0);ellipsoid(0,1.05f,0,.36f,.53f,.25f,r,g,b);ellipsoid(0,1.49f,0,.28f,.31f,.27f,.75f,.59f,.43f);ellipsoid(0,1.73f,0,.31f,.15f,.30f,r*.6f,g*.6f,b*.6f);ellipsoid(-.18f,.43f+walk,0,.14f,.40f,.16f,r*.7f,g*.7f,b*.7f);ellipsoid(.18f,.43f-walk,0,.14f,.40f,.16f,r*.7f,g*.7f,b*.7f);ellipsoid(-.36f,1.00f-walk*.5f,0,.14f,.36f,.15f,r,g,b);ellipsoid(.35f,1.08f+walk*.5f,0,.13f,.34f,.14f,r,g,b);ellipsoid(.30f,1.08f,.24f,.075f,.075f,.44f,.14f,.15f,.15f);glPopMatrix();
 /* Name tags stay upright and face the active camera. */
 static const char *callsign[MAX_PLAYERS]={"RANGER","FALCON","VIPER","SCORPION","COBRA","WOLF","EAGLE","GHOST","NOMAD","TALON","PHANTOM","MAMBA","HAWK","REAPER","SABER","ROGUE"};char tag[24];snprintf(tag,sizeof(tag),"%s",callsign[id]);if(font){glDisable(GL_LIGHTING);glDisable(GL_TEXTURE_2D);glColor3f(p->team?1.0f:.55f,p->team?.82f:.85f,p->team?.48f:1.0f);glPushMatrix();glTranslatef(p->x,2.28f+bounce,p->z);glRotatef((aimYaw+PI)*180/PI,0,1,0);glScalef(.008f,.008f,.008f);glRasterPos2f(-(float)strlen(tag)*6.0f,0);glListBase(font);glCallLists((GLsizei)strlen(tag),GL_UNSIGNED_BYTE,tag);glPopMatrix();if(graphicsQuality>=2)glEnable(GL_LIGHTING);}}
static void drawGun(Player *p){glClear(GL_DEPTH_BUFFER_BIT);perspective(67);float sway=sinf(bob)*.015f,recoil=shotFlash*1.1f,lower=p->reload>0?.25f:0,barrel=p->weapon==3?.56f:p->weapon==0?.16f:p->weapon==1?.24f:.32f;glTranslatef(.25f+sway,-.29f-lower,-.6f+recoil);glRotatef(-5,0,1,0);box(-.055f,-.05f,-.36f,.11f,.1f,.40f,-1,.18f,.19f,.20f);ellipsoid(-.018f,.005f,-.33f-barrel*.5f,.025f,.025f,barrel*.60f,.16f,.16f,.16f);box(-.065f,-.06f,-.40f,.13f,.09f,.16f,2,.8f,.8f,.8f);box(-.038f,-.20f,-.18f,.07f,p->weapon==0?.11f:.17f,.085f,-1,.16f,.17f,.17f);if(p->weapon==3)box(-.055f,.045f,-.48f,.11f,.09f,.18f,-1,.11f,.12f,.12f);box(-.09f,-.12f,-.06f,.13f,.1f,.24f,2,.9f,.9f,.9f);box(.035f,-.17f,-.06f,.1f,.1f,.15f,-1,.71f,.53f,.35f);if(shotFlash>0)ellipsoid(0,-.02f,-.76f,.055f,.05f,.09f,1,.8f,.22f);}
static void drawHud(void){char line[240];Player *p=&world.p[myId>=0?myId:0];ortho();rect(0,0,width,54,.035f,.05f,.06f,.87f);textAt(20,32,1,"DESERT STRIKE",1,.79f,.40f);snprintf(line,sizeof(line),"BLUE %02d    %02d:%02d    SAND %02d",world.score[0],(int)world.timeLeft/60,(int)world.timeLeft%60,world.score[1]);textAt(width/2-145,32,1,line,.94f,.9f,.8f);textAt(width-190,32,1,mode==1?"PRACTICE / 8":mode==2?"HOST / UDP 27016":"ONLINE",.65f,.76f,.78f);
rect(18,height-66,410,46,.03f,.045f,.05f,.86f);{static const char *wn[]={"PISTOL","SMG","RIFLE","SNIPER"};snprintf(line,sizeof(line),"HP %03d  %s %02d  $%d",p->hp,wn[p->weapon&3],p->ammo,p->credits);}textAt(32,height-37,1,line,1,.82f,.46f);snprintf(line,sizeof(line),"%s   K %d / D %d",p->team?"SAND":"BLUE",p->kills,p->deaths);textAt(width-290,height-37,1,line,.9f,.9f,.85f);
if(p->hp>0&&myId>=0){float cx=width/2,cy=height/2;rect(cx-11,cy-1,7,2,.8f,1,.7f,1);rect(cx+4,cy-1,7,2,.8f,1,.7f,1);rect(cx-1,cy-11,2,7,.8f,1,.7f,1);rect(cx-1,cy+4,2,7,.8f,1,.7f,1);}else{rect(width/2-190,height/2-35,380,65,0,0,0,.65f);snprintf(line,sizeof(line),myId<0?"CONNECTING TO SERVER...":"RESPAWN IN %.1f",p->respawn);textAt(width/2-150,height/2,1,line,1,.8f,.4f);}
if(p->reload>0)textAt(width/2-55,height/2+55,1,"RELOADING",1,.83f,.45f);
if(shopOpen){rect(width/2-245,height/2-150,490,300,.025f,.035f,.04f,.96f);textAt(width/2-210,height/2-112,1,"BUY MENU  (B TO CLOSE)",1,.8f,.42f);textAt(width/2-210,height/2-70,1,"1  SMG       $700     fast / light",.92f,.92f,.86f);textAt(width/2-210,height/2-32,1,"2  RIFLE    $1800    balanced",.92f,.92f,.86f);textAt(width/2-210,height/2+6,1,"3  SNIPER  $3200    high damage",.92f,.92f,.86f);snprintf(line,sizeof(line),"CASH: $%d   Buy with number key",p->credits);textAt(width/2-210,height/2+60,1,line,.95f,.76f,.39f);}
if(damageFlash>0)rect(0,54,width,height-54,.8f,0,0,damageFlash*.8f);
if(keys[VK_TAB]){rect(width/2-290,100,580,460,.02f,.03f,.04f,.94f);textAt(width/2-260,133,1,"TEAM        PLAYER         KILLS    DEATHS",1,.8f,.4f);int row=0;for(int i=0;i<16;i++)if(world.p[i].active){Player *q=&world.p[i];snprintf(line,sizeof(line),"%-8s    %s %02d          %3d       %3d",q->team?"SAND":"BLUE",mode==1&&i?"BOT":"PLAYER",i+1,q->kills,q->deaths);textAt(width/2-260,166+row++*23,1,line,i==myId?1:.73f,.8f,.8f);}}
if(help){rect(26,100,490,215,.02f,.03f,.04f,.92f);const char *h[]={"Custom move keys / mouse aim / left click fire","R reload / SHIFT walk / TAB scoreboard","B shop / 1-3 buy / ESC menu","F2 resolution / F3 graphics / F11 fullscreen","Three arena layouts / 10 minute rounds","Earn $300 per elimination / respawn in 3s","LAN/direct IP / up to 16 players"};for(int i=0;i<7;i++)textAt(42,132+i*25,1,h[i],.88f,.85f,.75f);}else textAt(22,78,1,"F1 HELP / F2 RESOLUTION / F3 QUALITY / F11 FULLSCREEN",.8f,.82f,.77f);
/* Small overhead radar: teammates only. */
float rx=width-146,ry=75;rect(rx-6,ry-6,134,134,.02f,.035f,.04f,.8f);for(int z=0;z<32;z++)for(int x=0;x<32;x++)if(tile(x,z)=='#')rect(rx+x*3.8f,ry+z*3.8f,3.8f,3.8f,.6f,.53f,.38f,.7f);for(int i=0;i<16;i++){Player *q=&world.p[i];if(q->active&&q->hp>0&&q->team==p->team)rect(rx+q->x/CELL*3.8f-2,ry+q->z/CELL*3.8f-2,4,4,i==myId?1:.3f,1,.7f,1);}}
static void drawMenu(void){char line[128];ortho();rect(0,0,width,height,.025f,.035f,.04f,.67f);rect(65,100,590,500,.035f,.045f,.05f,.92f);rect(65,100,5,500,1,.73f,.3f,1);textAt(95,153,1,"D E S E R T   S T R I K E",1,.8f,.43f);textAt(95,187,1,"AN ORIGINAL CLASSIC-STYLE FPS",.62f,.7f,.71f);
if(settingsOpen){rect(85,125,540,450,.025f,.035f,.04f,.98f);textAt(112,165,1,"SETTINGS  /  ESC TO RETURN",1,.8f,.43f);snprintf(line,sizeof(line),"VIDEO RESOLUTION: %dx%d  (click to cycle)",resolutions[resolutionIndex][0],resolutions[resolutionIndex][1]);textAt(112,213,1,line,.9f,.91f,.86f);snprintf(line,sizeof(line),"MAP QUALITY: %s  (click to cycle)",graphicsQuality==0?"LOW":graphicsQuality==1?"MEDIUM":"HIGH");textAt(112,253,1,line,.9f,.91f,.86f);for(int i=0;i<4;i++){char k[2]={(char)moveKeys[i],0};snprintf(line,sizeof(line),"%s MOVE: [%s]  (click, then press a letter)",i==0?"FORWARD":i==1?"BACKWARD":i==2?"LEFT":"RIGHT",k);textAt(112,303+i*43,1,line,rebindIndex==i?1:.83f,rebindIndex==i?.72f:.82f,rebindIndex==i?.35f:.8f);}textAt(112,535,1,"Quality changes textures, lighting, shadows and map details.",.62f,.72f,.70f);textAt(40,height-40,1,statusText,.94f,.79f,.5f);return;}
textAt(95,248,1,"[1]  PRACTICE WITH BOTS",.94f,.93f,.88f);textAt(95,293,1,"[2]  HOST A 16-PLAYER MATCH",.94f,.93f,.88f);textAt(95,338,1,"[3]  JOIN BY IPv4 ADDRESS",.94f,.93f,.88f);textAt(95,383,1,"[S]  SETTINGS",.83f,.84f,.75f);textAt(95,416,1,"[Q]  QUIT",.7f,.73f,.73f);textAt(95,451,1,selectedMap==0?"MAP: DESERT / M: CHANGE":selectedMap==1?"MAP: WESTERN FORT / M: CHANGE":"MAP: CANYON CROSSING / M: CHANGE",.83f,.71f,.51f);textAt(95,480,1,botDifficulty==0?"BOT DIFFICULTY: EASY / D: CHANGE":botDifficulty==1?"BOT DIFFICULTY: NORMAL / D: CHANGE":"BOT DIFFICULTY: HARD / D: CHANGE",.83f,.71f,.51f);snprintf(line,sizeof(line),"VIDEO: %dx%d / F2 CHANGE",resolutions[resolutionIndex][0],resolutions[resolutionIndex][1]);textAt(95,514,1,line,.65f,.7f,.7f);textAt(95,542,1,graphicsQuality==0?"QUALITY: LOW / F3 CHANGE":graphicsQuality==1?"QUALITY: MEDIUM / F3 CHANGE":"QUALITY: HIGH / F3 CHANGE",.65f,.7f,.7f);textAt(95,570,1,"F11 FULLSCREEN / B SHOP / S SETTINGS",.5f,.57f,.58f);textAt(40,height-40,1,statusText,.94f,.79f,.5f);if(joinEdit){rect(80,215,565,205,.06f,.08f,.09f,1);textAt(100,255,1,"SERVER IPv4 (UDP port 27016)",1,.8f,.4f);rect(100,275,520,45,.015f,.025f,.03f,1);textAt(114,304,1,address,1,1,1);textAt(100,355,1,"ENTER: connect / BACKSPACE: edit / ESC: cancel",.8f,.83f,.8f);}}
static void render(void){glViewport(0,0,width,height);glClearColor(.67f,.73f,.75f,1);glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT);glEnable(GL_DEPTH_TEST);glDisable(GL_BLEND);perspective(78);float x=9,z=12,y=1.65f,yaw=.8f,pitch=0;if(mode&&myId>=0){Player *p=&world.p[myId];x=p->x;z=p->z;y=p->hp>0?1.65f:.6f;yaw=aimYaw;pitch=aimPitch;}else if(!mode){x=40;z=56;y=9;yaw=.6f;pitch=-.20f;}glRotatef(-pitch*180/PI,1,0,0);glRotatef(180-yaw*180/PI,0,1,0);glTranslatef(-x,-y,-z);if(graphicsQuality>=2){GLfloat ambient[]={.30f,.30f,.29f,1},diffuse[]={.94f,.87f,.75f,1},sun[]={-.35f,1.0f,.25f,0};glEnable(GL_LIGHTING);glEnable(GL_LIGHT0);glEnable(GL_COLOR_MATERIAL);glColorMaterial(GL_FRONT_AND_BACK,GL_AMBIENT_AND_DIFFUSE);glLightModelfv(GL_LIGHT_MODEL_AMBIENT,ambient);glLightfv(GL_LIGHT0,GL_AMBIENT,ambient);glLightfv(GL_LIGHT0,GL_DIFFUSE,diffuse);glLightfv(GL_LIGHT0,GL_POSITION,sun);}else{glDisable(GL_LIGHTING);glDisable(GL_LIGHT0);}GLfloat fogColor[]={.67f,.73f,.75f,1};glEnable(GL_FOG);glFogi(GL_FOG_MODE,GL_LINEAR);glFogfv(GL_FOG_COLOR,fogColor);glFogf(GL_FOG_START,42);glFogf(GL_FOG_END,108);glCallList(arenaList);if(graphicsQuality>=2)glEnable(GL_LIGHTING);else glDisable(GL_LIGHTING);for(int i=0;i<16;i++)if(world.p[i].active&&world.p[i].hp>0&&i!=myId)drawPlayer(&world.p[i]);glDisable(GL_FOG);if(mode){if(myId>=0&&world.p[myId].hp>0)drawGun(&world.p[myId]);drawHud();}else drawMenu();SwapBuffers(dc);}
static LRESULT CALLBACK wndProc(HWND h,UINT msg,WPARAM w,LPARAM l){switch(msg){case WM_CLOSE:running=0;return 0;case WM_SIZE:width=LOWORD(l);height=HIWORD(l);if(height<1)height=1;if(mode&&w!=SIZE_MINIMIZED)captureMouse();return 0;case WM_LBUTTONDOWN:if(!mode&&!joinEdit){int mx=LOWORD(l),my=HIWORD(l);if(settingsOpen){if(mx>=90&&mx<=620&&my>=188&&my<=224){int old=resolutionIndex;resolutionIndex=(resolutionIndex+1)%5;if(!applyResolution())resolutionIndex=old;}else if(mx>=90&&mx<=620&&my>=228&&my<=267)cycleGraphicsQuality();else if(mx>=90&&mx<=620&&my>=284&&my<=456){int row=(my-284)/43;if(row>=0&&row<4)rebindIndex=row;}return 0;}if(mx>=80&&mx<=635){if(my>=220&&my<=260)startGame(1);else if(my>=265&&my<=307)startGame(2);else if(my>=312&&my<=355){joinEdit=1;skipJoinChar=0;}else if(my>=365&&my<=405)settingsOpen=1;else if(my>=400&&my<=438)running=0;}}return 0;case WM_ACTIVATE:focused=LOWORD(w)!=WA_INACTIVE;memset(keys,0,sizeof(keys));if(focused&&mode)captureMouse();else releaseMouse();return 0;case WM_KEYDOWN:if(w<256)keys[w]=1;if(!mode&&settingsOpen&&!(l&(1<<30))){if(rebindIndex>=0){if(w>='A'&&w<='Z'){if(w=='R'||w=='B')snprintf(statusText,sizeof(statusText),"R and B are reserved for reload and the shop.");else{int used=0;for(int i=0;i<4;i++)if(i!=rebindIndex&&moveKeys[i]==(int)w)used=1;if(used)snprintf(statusText,sizeof(statusText),"That movement key is already assigned.");else{moveKeys[rebindIndex]=(int)w;statusText[0]=0;}}}rebindIndex=-1;return 0;}if(w==VK_ESCAPE)settingsOpen=0;return 0;}if(mode&&!(l&(1<<30))&&w=='B'){shopOpen=!shopOpen;pendingBuy=0;}if(mode&&shopOpen&&!(l&(1<<30))&&w>='1'&&w<='3')pendingBuy=(int)(w-'0');if(!mode&&!(l&(1<<30))&&!joinEdit){if(w=='M'){selectedMap=(selectedMap+1)%3;rebuildArena();}if(w=='D')botDifficulty=(botDifficulty+1)%3;}if(w==VK_ESCAPE){if(shopOpen)shopOpen=0;else if(joinEdit)joinEdit=0;else if(mode)menu("Match left. Choose a mode.");else running=0;}if(w==VK_F11&&!(l&(1<<30)))toggleFullscreen();if(w==VK_F2&&!(l&(1<<30))){int oldResolution=resolutionIndex;resolutionIndex=(resolutionIndex+1)%5;if(!applyResolution())resolutionIndex=oldResolution;}if(w==VK_F3&&!(l&(1<<30)))cycleGraphicsQuality();if(w==VK_F1&&!(l&(1<<30)))help=!help;if(!mode&&!joinEdit){if(w=='1')startGame(1);if(w=='2')startGame(2);if(w=='3'){joinEdit=1;skipJoinChar=1;}if(w=='S')settingsOpen=1;if(w=='Q')running=0;}else if(!mode&&joinEdit&&w==VK_RETURN)startGame(3);return 0;case WM_KEYUP:if(w<256)keys[w]=0;return 0;case WM_CHAR:if(joinEdit){if(skipJoinChar){skipJoinChar=0;return 0;}int n=(int)strlen(address);if(w==8&&n)address[n-1]=0;else if((w=='.'||(w>='0'&&w<='9'))&&n<63){address[n]=(char)w;address[n+1]=0;}}return 0;}return DefWindowProcA(h,msg,w,l);}
static Input localInput(float dt){Input in={0};in.yaw=aimYaw;in.pitch=aimPitch;if(!focused)return in;POINT center={width/2,height/2},p;ClientToScreen(window,&center);GetCursorPos(&p);aimYaw-=(p.x-center.x)*.0023f;aimPitch=clampf(aimPitch-(p.y-center.y)*.0023f,-1.3f,1.3f);SetCursorPos(center.x,center.y);in.yaw=aimYaw;in.pitch=aimPitch;if(!shopOpen){in.forward=(float)(keys[moveKeys[0]]-keys[moveKeys[1]]);in.side=(float)(keys[moveKeys[3]]-keys[moveKeys[2]]);if(GetAsyncKeyState(VK_LBUTTON)&0x8000)in.buttons|=1;if(keys['R'])in.buttons|=2;if(keys[VK_SHIFT])in.buttons|=4;if(in.forward||in.side)bob+=dt*10;}if(pendingBuy){in.buttons|=8u<<(pendingBuy-1);pendingBuy=0;}return in;}
int WINAPI WinMain(HINSTANCE instance,HINSTANCE previous,LPSTR command,int show){(void)previous;(void)show;QueryPerformanceFrequency(&frequency);WSADATA ws;if(WSAStartup(MAKEWORD(2,2),&ws)){MessageBoxA(NULL,"Winsock initialization failed.","Desert Strike",MB_ICONERROR);return 1;}dedicated=strstr(command,"--server")!=NULL;initWorld(&world);
if(dedicated){AllocConsole();if(!openNet(1)){printf("Could not bind UDP 27016.\n");Sleep(5000);return 1;}printf("Desert Strike dedicated server\nUDP 27016 / maximum 16 players / no bots\nClose this window to stop.\n");double last=now(),acc=0;while(1){double t=now();acc+=fmin(t-last,.1);last=t;serverNetwork(t);while(acc>=1.0/60){stepWorld(&world,inputs,1.0f/60);acc-=1.0/60;}Sleep(1);}}
WNDCLASSA wc;memset(&wc,0,sizeof(wc));wc.style=CS_OWNDC;wc.lpfnWndProc=wndProc;wc.hInstance=instance;wc.hCursor=LoadCursor(NULL,IDC_ARROW);wc.lpszClassName="DesertStrikeWindow";RegisterClassA(&wc);RECT wr={0,0,width,height};AdjustWindowRect(&wr,WS_OVERLAPPEDWINDOW,FALSE);window=CreateWindowA(wc.lpszClassName,"Desert Strike - Arena FPS",WS_OVERLAPPEDWINDOW|WS_VISIBLE,CW_USEDEFAULT,CW_USEDEFAULT,wr.right-wr.left,wr.bottom-wr.top,NULL,NULL,instance,NULL);dc=GetDC(window);PIXELFORMATDESCRIPTOR pfd;memset(&pfd,0,sizeof(pfd));pfd.nSize=sizeof(pfd);pfd.nVersion=1;pfd.dwFlags=PFD_DRAW_TO_WINDOW|PFD_SUPPORT_OPENGL|PFD_DOUBLEBUFFER;pfd.iPixelType=PFD_TYPE_RGBA;pfd.cColorBits=24;pfd.cDepthBits=24;int pf=ChoosePixelFormat(dc,&pfd);if(!pf||!SetPixelFormat(dc,pf,&pfd)||(glrc=wglCreateContext(dc))==NULL||!wglMakeCurrent(dc,glrc)){MessageBoxA(window,"OpenGL initialization failed. Install the video driver.","Desert Strike",MB_ICONERROR);return 1;}HFONT f=CreateFontA(-17,0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,ANSI_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,ANTIALIASED_QUALITY,FIXED_PITCH,"Consolas");SelectObject(dc,f);font=glGenLists(256);wglUseFontBitmapsA(dc,0,256,font);createTextures();arenaList=glGenLists(1);glNewList(arenaList,GL_COMPILE);buildArena();glEndList();soundInit();double last=now(),acc=0;int lastHp=100;MSG msg;while(running){while(PeekMessage(&msg,NULL,0,0,PM_REMOVE)){if(msg.message==WM_QUIT)running=0;TranslateMessage(&msg);DispatchMessage(&msg);}double t=now();float dt=(float)fmin(t-last,.1);last=t;shotFlash=fmaxf(0,shotFlash-dt);damageFlash=fmaxf(0,damageFlash-dt);if(mode){Input in=localInput(dt);if(mode==3){clientNetwork(t);if(mode==3&&myId>=0&&t>=netNext){sendRequest(3,in);netNext=t+1.0/60;}}else{inputs[0]=in;if(mode==2)serverNetwork(t);acc+=dt;while(acc>=1.0/60){if(mode==1)for(int i=1;i<8;i++)inputs[i]=botInput(i);stepWorld(&world,inputs,1.0f/60);acc-=1.0/60;}}if(myId>=0){Player *p=&world.p[myId];for(int si=0;si<16;si++){Player *sp=&world.p[si];if(sp->active&&sp->shot!=seenShots[si]){seenShots[si]=sp->shot;float dx=sp->x-p->x,dz=sp->z-p->z;if(si==myId)shotFlash=.07f;playGunSound(sqrtf(dx*dx+dz*dz));}}if(p->hp<lastHp)damageFlash=.25f;if(lastHp<=0&&p->hp>0){aimYaw=p->yaw;aimPitch=0;}lastHp=p->hp;}}else acc=0;if(!IsIconic(window))render();else Sleep(25);double elapsed=now()-t;if(elapsed<1.0/60)Sleep((DWORD)((1.0/60-elapsed)*1000));}stopNet();PlaySoundA(NULL,NULL,0);if(fullScreen)ChangeDisplaySettingsA(NULL,0);releaseMouse();glDeleteLists(arenaList,1);glDeleteLists(font,256);glDeleteTextures(4,tex);wglMakeCurrent(NULL,NULL);wglDeleteContext(glrc);DeleteObject(f);ReleaseDC(window,dc);DestroyWindow(window);WSACleanup();return 0;}
